name: Build Spring Cloud Gateway with JDK 8

on:
  push:
    branches: [ 3.1.x ]
  pull_request:
    branches: [ 3.1.x ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'

      - name: Make mvnw executable
        run: chmod +x ./mvnw

      - name: Build and run tests (Maven)
        run: ./mvnw -B -ntp clean verify

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gateway-artifacts-jdk8
          path: |
            **/target/*.jar
            **/target/*.war
          retention-days: 7
