# .github/workflows/release.yml
name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Build Project
      run: |
        chmod +x ./mvnw
        ./mvnw clean package -DskipTests
        
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/*.jar
          target/*.war
        body: |
          自动构建的 Spring Cloud Gateway 发布版本
          
          包含文件:
          - 可执行 JAR 文件
          - 源码 JAR 文件
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
